---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kepler-flask-deployment
  labels:
    app: kepler-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kepler-flask
  template:
    metadata:
      labels:
        app: kepler-flask
    spec:
      containers:
        - name: kepler-flask
          imagePullPolicy: Always
          image: zbickham/kepler-api:0.1
          env: 
          - name: REDIS_IP
            value: "10.105.4.24" 
          ports:
          - name: http
            containerPort: 5000
